### ISSUE TITLE
Not works after upgrade to 8.5.0-beta1 (2022-04-06)

### ISSUE THREAD

**Issue by baur** [WilliamVenner/grafana-timepicker-buttons#31]
The plugin does not work after upgrade to 8.5.0-beta1 (2022-04-06)
Please help, this is the only plugin in the enterprise

**Environment**:
- Grafana version: 8.5.0-beta1
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Chrome

**Comment by baur** [comment]
```
Failed to load resource: the server responded with a status of 400 (Bad Request) -> http://server:3002/api/ds/query
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'values')
    at eval (Panel.tsx:21:34)
    at Array.forEach (<anonymous>)
    at eval (module.js:1:26224)
    at rs (react-dom.production.min.js:157:137)
    at Wi (react-dom.production.min.js:267:460)
    at Su (react-dom.production.min.js:250:347)
    at ku (react-dom.production.min.js:250:278)
    at wu (react-dom.production.min.js:250:138)
    at hu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
si @ react-dom.production.min.js:216
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
da @ react-dom.production.min.js:131
fi @ react-dom.production.min.js:220
Tu @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ho @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:252
hu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ho @ react-dom.production.min.js:122
Vo @ react-dom.production.min.js:123
Zo @ react-dom.production.min.js:122
cu @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
g.setState @ react.production.min.js:12
onDataUpdate @ PanelChrome.tsx:336
next @ PanelChrome.tsx:237
e.next @ Subscriber.js:96
t._next @ Subscriber.js:63
t.next @ Subscriber.js:34
(anonymous) @ map.js:7
i._next @ OperatorSubscriber.js:15
t.next @ Subscriber.js:34
(anonymous) @ mergeInternals.js:25
i._next @ OperatorSubscriber.js:15
t.next @ Subscriber.js:34
(anonymous) @ innerFrom.js:51
e._trySubscribe @ Observable.js:38
(anonymous) @ Observable.js:32
a @ errorContext.js:19
e.subscribe @ Observable.js:23
b @ mergeInternals.js:19
g @ mergeInternals.js:14
i._next @ OperatorSubscriber.js:15
t.next @ Subscriber.js:34
(anonymous) @ Subject.js:41
a @ errorContext.js:19
...
(anonymous) @ innerFrom.js:61
Show 99 more frames

```
```
:3002/d/OIdgwXgnk/ne…&inspectTab=query:1 Uncaught (in promise) Object
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'values')
    at eval (Panel.tsx:21:34)
    at Array.forEach (<anonymous>)
    at eval (module.js:1:26224)
    at rs (react-dom.production.min.js:157:137)
    at Wi (react-dom.production.min.js:267:460)
    at Su (react-dom.production.min.js:250:347)
    at ku (react-dom.production.min.js:250:278)
    at wu (react-dom.production.min.js:250:138)
    at hu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
```

**Comment by baur** [comment]
Not works with Grafana  v8.5.0

**Comment by baur** [comment]
Select date works and reflects on URL and on time picker but does not applies

**Comment by Sulomus** [comment]
+1

Doesn't work even on my Grafana Cloud Pro license!  :( 

Exactly what you are talking about! I can see the URL changes but it doesn't affect / refresh the dashboard!

**Comment by brubbel** [comment]
Confirmed, no refresh on grafana cloud. Also, the selected date is delayed by 1 click.

**Comment by baur** [comment]
Looks like Grafana [bug](https://github.com/grafana/grafana/issues/48652)

**Comment by Sulomus** [comment]
Resolved! :)
